[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd.err

[program:edge-runtime]
command=edge-runtime start --main-service /home/deno/functions/main
autorestart=true
stdout_logfile=/var/log/supervisor/edge.log
stderr_logfile=/var/log/supervisor/edge.err
environment=JWT_SECRET="PfDXQ7rCKlmIIUgo4lep8LTBUVV9yI388vuF8cA+",SUPABASE_URL="http://kong:8000",VERIFY_JWT="true",DENO_DIR="/tmp/deno_cache",PORT="9999",DENO_LOG_LEVEL="debug"